// Generated by FlutterFever JSON to Dart Tool
// Root model: Productlistmodel

import 'package:flutter2/products/models/product_model.dart';

class ProductlistModel {
  final List<ProductModel> data;

  ProductlistModel({required this.data});

  ProductlistModel copyWith({List<ProductModel>? data}) {
    return ProductlistModel(data: data ?? this.data);
  }

  factory ProductlistModel.fromMap(Map<String, dynamic> json) {
    return ProductlistModel(
      data: json['data'] != null
          ? List<ProductModel>.from(
              (json['data'] as List).map(
                (x) => ProductModel.fromMap(Map<String, dynamic>.from(x)),
              ),
            )
          : [],
    );
  }

  Map<String, dynamic> toMap() {
    return {'data': data.map((x) => x.toMap()).toList()};
  }
}
