// Generated by FlutterFever JSON to Dart Tool
// Root model: Productdetailmodel

class Productdetailmodel {
  final String message;

  Productdetailmodel({required this.message});

  Productdetailmodel copyWith({String? message}) {
    return Productdetailmodel(message: message ?? this.message);
  }

  factory Productdetailmodel.fromMap(Map<String, dynamic> json) {
    return Productdetailmodel(message: json['message']);
  }

  Map<String, dynamic> toMap() {
    return {'message': message};
  }
}
